# Generated by Django 2.2.1 on 2019-09-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20190908_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='exam_date',
            field=models.DateField(verbose_name='exam date'),
        ),
    ]
