# Generated by Django 2.2.1 on 2019-09-05 06:31

from django.db import migrations, models
import django.db.models.deletion
import messaging.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signUp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatId', models.IntegerField(default=messaging.models.Chat.make_chatId, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageTT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date sent')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.Chat')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiversTT', to='signUp.Teacher')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendersTT', to='signUp.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='MessageTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date sent')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.Chat')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiversTS', to='signUp.Student')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendersTS', to='signUp.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='MessageST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date sent')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.Chat')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiversST', to='signUp.Teacher')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendersST', to='signUp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='MessageSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date sent')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.Chat')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiversSS', to='signUp.Student')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendersSS', to='signUp.Student')),
            ],
        ),
    ]
