# Generated by Django 2.2.1 on 2019-09-05 06:31

from django.db import migrations, models
import signUp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_no', models.CharField(max_length=200)),
                ('course_name', models.CharField(max_length=200)),
                ('level', models.IntegerField(default=0)),
                ('term', models.IntegerField(default=0)),
                ('course_detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, unique=True)),
                ('role', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('conf_password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('teacher_id', models.IntegerField(default=signUp.models.Teacher.make_id, unique=True)),
                ('profile_pic', models.ImageField(blank=True, default='teacher/profile/pics/profile.png', null=True, upload_to='teacher/profile/pics')),
                ('role', models.CharField(default='Teacher', max_length=200)),
                ('assignedCourses', models.ManyToManyField(blank=True, related_name='assignedTeachers', to='signUp.Course')),
                ('courses', models.ManyToManyField(related_name='teachers', to='signUp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('conf_password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('student_id', models.IntegerField(default=signUp.models.Student.make_id, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(blank=True, default='student/profile/pics/profile.png', null=True, upload_to='student/profile/pics')),
                ('registered', models.BooleanField(default=False)),
                ('role', models.CharField(default='Student', max_length=200)),
                ('courses', models.ManyToManyField(related_name='students', to='signUp.Course')),
                ('quizzes', models.ManyToManyField(related_name='students', to='classroom.Quiz')),
            ],
        ),
    ]
